POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
    "id":4,
    "titulo": "Aprende Node Js",
    "language": "Javascript",
    "vistas": 44567,
    "nivel": "intermedio"
}

###

PUT http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "titulo": "Aprende Python Intermedio con Proyectos",
    "language": "Python",
    "vistas": 4747635,
    "nivel": "intermedio"
}

###


PATCH  http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "nivel": "avanzado"
}


###


DELETE   http://localhost:3000/api/cursos/programacion/1 HTTP/1.1
